import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

import Layout from '../components/Layout'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { t } = useTranslation()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <h1 className={styles.title}>
            {t('welcome')} <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <div className={styles.grid}>
            <Link href="/service/register">
              <div className={styles.card}>
                <h2>Register &rarr;</h2>
              </div>
            </Link>
            <Link href="/service/product">
              <div className={styles.card}>
                <h2>Product &rarr;</h2>
              </div>
            </Link>
            <Link href="/service/payment">
              <div className={styles.card}>
                <h2>Payment &rarr;</h2>
              </div>
            </Link>
          </div>
        </main>
      </Layout>
    </div>
  )
}

interface ServerProps {
  locale: string,
  query: {
    feature: string
  }
}

export async function getServerSideProps({ locale, query }: ServerProps) {
  console.log('Get query from server', query)

  return {
    props: {
      ...await serverSideTranslations(locale, ['common']),
    },
  }
}

export default Home
